"""Phase 3: OCI image build using a dynamically-generated BUILD.bazel."""

from __future__ import annotations

import dataclasses
import re
import subprocess
from pathlib import Path

from mlody.common.image_builder.errors import BazelBuildError
from mlody.common.image_builder.log import info
from mlody.common.image_builder.phases.clone import CloneResult

# Package written into the clone dir for OCI image assembly.
# Leading underscore keeps it out of normal Bazel query results.
_DYN_PKG = "_dynamic_image"

_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_]")


@dataclasses.dataclass(frozen=True)
class BazelResult:
    stdout: str
    stderr: str


def _target_subdir(label: str) -> str:
    """Derive the subdirectory name for a target's outputs inside the image.

    Uses the name component of the label (the part after ':'), or the last
    path segment if no colon is present.

      //mlody/cli:mlody              -> mlody
      //repo/smoketest/python/simple:simple  -> simple
      //foo/bar                      -> bar
    """
    if ":" in label:
        return label.split(":")[-1]
    return label.rstrip("/").split("/")[-1]


def _safe_rule_name(subdir: str) -> str:
    """Convert a subdirectory name to a valid Starlark rule name."""
    return _SAFE_NAME_RE.sub("_", subdir)


def _build_labels(sha: str, clone_result: CloneResult) -> dict[str, str]:
    """Derive OCI image labels from the clone result."""
    dirty = bool(clone_result.applied_patch or clone_result.applied_untracked)
    labels: dict[str, str] = {
        "org.opencontainers.image.revision": sha,
        "com.polymath.mlody.dirty": "true" if dirty else "false",
    }
    if dirty:
        changed_files = len(
            {
                line
                for line in clone_result.applied_patch.splitlines()
                if line.startswith("diff ")
            }
        )
        labels["com.polymath.mlody.dirty_files_changed"] = str(changed_files)
        labels["com.polymath.mlody.dirty_untracked"] = str(
            len(clone_result.applied_untracked)
        )
    return labels


def _write_image_build(
    clone_dir: Path,
    targets: list[str],
    labels: dict[str, str],
    base_image: str,
) -> None:
    """Write a BUILD.bazel for OCI image assembly into the clone workspace.

    Each target gets its own pkg_tar with a package_dir equal to
    /<target-name>, so outputs from different targets never conflict.
    All per-target layers are combined in a single oci_image target.

    Layout inside the image:
      /<name>/<binary>
      /<name>/<binary>.py
      /<name>/<binary>.venv.pth
      ...
    """
    pkg_dir = clone_dir / _DYN_PKG
    pkg_dir.mkdir(exist_ok=True)

    tar_rules: list[str] = []
    tar_names: list[str] = []
    for label in targets:
        subdir = _target_subdir(label)
        rule_name = f"layer_{_safe_rule_name(subdir)}"
        tar_names.append(f'":{rule_name}"')
        tar_rules.append(
            f'pkg_tar(\n'
            f'    name = "{rule_name}",\n'
            f'    srcs = ["{label}"],\n'
            f'    package_dir = "/{subdir}",\n'
            f')\n'
        )

    tars_starlark = ",\n        ".join(tar_names)
    labels_starlark = "\n".join(
        f'        "{k}": "{v}",' for k, v in labels.items()
    )
    tar_block = "\n".join(tar_rules)

    content = f"""\
# Auto-generated by mlody-image-builder — do not commit.
load("@rules_oci//oci:defs.bzl", "oci_image")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

{tar_block}
oci_image(
    name = "image",
    base = "{base_image}",
    tars = [
        {tars_starlark},
    ],
    labels = {{
{labels_starlark}
    }},
)
"""
    (pkg_dir / "BUILD.bazel").write_text(content)


def run_bazel_build(
    sha: str,
    clone_result: CloneResult,
    targets: list[str],
    base_image: str = "@distroless_python3",
) -> BazelResult:
    """Build the combined OCI image inside the clone directory.

    Writes a BUILD.bazel at clone_dir/_dynamic_image/ with one pkg_tar per
    target (each under its own /<name>/ subdirectory) to avoid filename
    conflicts, then invokes `bazel build //_dynamic_image:image`.

    Raises BazelBuildError on non-zero bazel exit.
    """
    clone_dir = clone_result.path
    labels = _build_labels(sha, clone_result)
    _write_image_build(clone_dir, targets, labels, base_image)

    target = f"//{_DYN_PKG}:image"
    cmd = ["bazel", "build", target]
    info("build", targets=targets, cmd=" ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=clone_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise BazelBuildError(
            f"bazel build {target} failed",
            targets=targets,
            returncode=result.returncode,
            stderr=result.stderr.strip(),
        )

    info("build", status="success", targets=targets)
    return BazelResult(stdout=result.stdout, stderr=result.stderr)
