"""Phase 3: OCI image build using a dynamically-generated BUILD.bazel."""

from __future__ import annotations

import dataclasses
import subprocess
from pathlib import Path

from mlody.common.image_builder.errors import BazelBuildError
from mlody.common.image_builder.log import info

# Package written into the clone dir for OCI image assembly.
# Leading underscore keeps it out of normal Bazel query results.
_DYN_PKG = "_dynamic_image"


@dataclasses.dataclass(frozen=True)
class BazelResult:
    stdout: str
    stderr: str


def _write_image_build(clone_dir: Path, targets: list[str]) -> None:
    """Write a BUILD.bazel for OCI image assembly into the clone workspace.

    Creates clone_dir/_dynamic_image/BUILD.bazel with pkg_tar + oci_image
    targets referencing each of the provided Bazel labels. Labels use the
    same // notation as in the clone's own workspace — no cross-repo
    references needed.
    """
    pkg_dir = clone_dir / _DYN_PKG
    pkg_dir.mkdir(exist_ok=True)

    srcs = "\n".join(f'        "{t}",' for t in targets)
    content = f"""\
# Auto-generated by mlody-image-builder — do not commit.
load("@rules_oci//oci:defs.bzl", "oci_image")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

pkg_tar(
    name = "layer",
    srcs = [
{srcs}
    ],
)

oci_image(
    name = "image",
    base = "@distroless_base",
    tars = [":layer"],
)
"""
    (pkg_dir / "BUILD.bazel").write_text(content)


def run_bazel_build(clone_dir: Path, targets: list[str]) -> BazelResult:
    """Build the combined OCI image inside clone_dir.

    Writes a BUILD.bazel at clone_dir/_dynamic_image/ that assembles the
    provided targets into a single OCI image via pkg_tar + oci_image, then
    invokes `bazel build //_dynamic_image:image`.

    Raises BazelBuildError on non-zero bazel exit.
    """
    _write_image_build(clone_dir, targets)

    target = f"//{_DYN_PKG}:image"
    cmd = ["bazel", "build", target]
    info("build", targets=targets, cmd=" ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=clone_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise BazelBuildError(
            f"bazel build {target} failed",
            targets=targets,
            returncode=result.returncode,
            stderr=result.stderr.strip(),
        )

    info("build", status="success", targets=targets)
    return BazelResult(stdout=result.stdout, stderr=result.stderr)
