"""Phase 3: OCI image build using a dynamically-generated BUILD.bazel."""

from __future__ import annotations

import dataclasses
import subprocess
from pathlib import Path

from mlody.common.image_builder.errors import BazelBuildError
from mlody.common.image_builder.log import info
from mlody.common.image_builder.phases.clone import CloneResult

# Package written into the clone dir for OCI image assembly.
# Leading underscore keeps it out of normal Bazel query results.
_DYN_PKG = "_dynamic_image"


@dataclasses.dataclass(frozen=True)
class BazelResult:
    stdout: str
    stderr: str


def _build_labels(sha: str, clone_result: CloneResult) -> dict[str, str]:
    """Derive OCI image labels from the clone result."""
    dirty = bool(clone_result.applied_patch or clone_result.applied_untracked)
    labels: dict[str, str] = {
        "org.opencontainers.image.revision": sha,
        "com.polymath.mlody.dirty": "true" if dirty else "false",
    }
    if dirty:
        # Count hunks (lines starting with @@) as a proxy for changed regions
        changed_files = len(
            {
                line[6:]  # strip "diff --git a/"
                for line in clone_result.applied_patch.splitlines()
                if line.startswith("diff ")
            }
        )
        labels["com.polymath.mlody.dirty_files_changed"] = str(changed_files)
        labels["com.polymath.mlody.dirty_untracked"] = str(
            len(clone_result.applied_untracked)
        )
    return labels


def _write_image_build(
    clone_dir: Path,
    targets: list[str],
    labels: dict[str, str],
) -> None:
    """Write a BUILD.bazel for OCI image assembly into the clone workspace.

    Creates clone_dir/_dynamic_image/BUILD.bazel with pkg_tar + oci_image
    targets referencing each of the provided Bazel labels. OCI image labels
    are embedded directly in the oci_image rule.
    """
    pkg_dir = clone_dir / _DYN_PKG
    pkg_dir.mkdir(exist_ok=True)

    srcs = "\n".join(f'        "{t}",' for t in targets)
    labels_starlark = "\n".join(
        f'        "{k}": "{v}",' for k, v in labels.items()
    )
    content = f"""\
# Auto-generated by mlody-image-builder — do not commit.
load("@rules_oci//oci:defs.bzl", "oci_image")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

pkg_tar(
    name = "layer",
    srcs = [
{srcs}
    ],
)

oci_image(
    name = "image",
    base = "@distroless_base",
    tars = [":layer"],
    labels = {{
{labels_starlark}
    }},
)
"""
    (pkg_dir / "BUILD.bazel").write_text(content)


def run_bazel_build(
    sha: str,
    clone_result: CloneResult,
    targets: list[str],
) -> BazelResult:
    """Build the combined OCI image inside the clone directory.

    Writes a BUILD.bazel at clone_dir/_dynamic_image/ that assembles the
    provided targets into a single OCI image via pkg_tar + oci_image, with
    OCI labels recording the commit SHA and dirty-build metadata.
    Invokes `bazel build //_dynamic_image:image`.

    Raises BazelBuildError on non-zero bazel exit.
    """
    clone_dir = clone_result.path
    labels = _build_labels(sha, clone_result)
    _write_image_build(clone_dir, targets, labels)

    target = f"//{_DYN_PKG}:image"
    cmd = ["bazel", "build", target]
    info("build", targets=targets, cmd=" ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=clone_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise BazelBuildError(
            f"bazel build {target} failed",
            targets=targets,
            returncode=result.returncode,
            stderr=result.stderr.strip(),
        )

    info("build", status="success", targets=targets)
    return BazelResult(stdout=result.stdout, stderr=result.stderr)
